# Настройки линтинга
[tool.ruff.lint]
select = [
    "E",   # PEP 8 ошибки
    "F",   # Форматирование
    "B",   # Баги
    # Удалено COM812, так как оно конфликтует с форматтером
]
ignore = [
    "E501",  # Игнорировать длину строки (если используете Black)
    "COM812" # Конфликтующее правило
]

# Настройки форматирования (если используете Ruff Formatter)
[tool.ruff.format]
docstring-code-format = true