[tool.ruff]
line-length = 120  # Максимальная длина строки
select = [         # Включаемые правила
    "E",   # Ошибки (PEP 8)
    "F",   # Ошибки форматирования
    "I",   # Сортировка импортов
    "B",   # Баги
    "C",   # Сложность кода
    "SIM", # Упрощения кода
]
ignore = ["E501", "COM812"]  # Игнорируемые правила